import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join } from 'node:path';
import { configPath } from '../config.js';

/**
 * The pinned-binary shim: how a wake stops playing PATH roulette with its own toolchain.
 *
 * A woken session's musterd hooks are installed machine-wide and call a BARE `musterd`
 * (`command -v musterd >/dev/null && musterd session start --stdin`), so **PATH alone** decides
 * which build of musterd runs inside a wake. The host LaunchAgent's PATH is not the operator's
 * interactive PATH, and on the dogfood machine (measured 2026-07-29, lane `01KYQMM141`) it resolved
 * `/opt/homebrew/bin/musterd` — a Homebrew tarball frozen at the 2026-07-23 release, 147 commits of
 * hook logic behind the live dist the auto-refresher rebuilds. Both report version `0.3.1`, so
 * nothing could see the skew by version; only the ADR 130/135 `dist/build.json` ref differs.
 *
 * The fix is not a better PATH — it is *not inheriting the question*. Ordering makes PATH fixes
 * fragile in a way that is easy to get backwards: the sibling auto-refresh plist lists
 * `/opt/homebrew/bin` BEFORE `~/Library/pnpm`, so copying its PATH shape into the host plist still
 * resolves the frozen tarball. And repointing Homebrew's own symlink is machine surgery that dies on
 * the next `brew upgrade` (the Cellar trap already recorded in `resolveLiveCtx`).
 *
 * So the host exports the one binary it knows is correct: **the one it is itself running**. It writes
 * a tiny shim that execs its own `node` + entry, and prepends that directory to the spawned
 * harness's PATH. A woken session's musterd is then the actuator's build *by construction*, on any
 * machine layout — including a Homebrew-only user install, where the brew binary IS the actuator's
 * and pinning it is still the right answer. Nothing here edits a plist or a package manager, so the
 * fix ships through the auto-refresher like any other code change.
 *
 * Best-effort by contract, like every musterd hook: if the shim cannot be written the wake proceeds
 * on the inherited PATH rather than failing. A degraded pin is a stale hook; a thrown pin is a dead
 * rail.
 */

/** The shim's absolute path inside `dir`. Named `musterd` because that is what the hooks call. */
export function pinnedPath(dir: string): string {
  return join(dir, 'musterd');
}

export interface PinnedMusterdOpts {
  /** The actuator's own interpreter — `process.execPath`. */
  node: string;
  /** The actuator's own CLI entry — `process.argv[1]`, the live `dist/bin.js`. */
  binJs: string;
}

/**
 * Ensure `~/.musterd/bin/musterd` execs `node binJs`, and return the directory to prepend to a
 * woken harness's PATH. `undefined` means "could not pin" — the caller leaves PATH alone.
 *
 * Idempotent by content, so the common case touches no bytes: the host calls this on every wake.
 */
export function ensurePinnedMusterd(opts: PinnedMusterdOpts): string | undefined {
  // A relative entry would resolve against the *seat's* cwd inside the woken session, silently
  // pinning nothing (or the wrong thing). Absolute or not at all.
  if (!isAbsolute(opts.node) || !isAbsolute(opts.binJs)) return undefined;

  const dir = join(dirname(configPath()), 'bin');
  const shim = pinnedPath(dir);
  // Same shape Homebrew's own wrapper uses — exec, so no extra process survives the wake, and
  // "$@" passes the hook's arguments through untouched.
  const body = `#!/bin/sh\n# generated by musterd host — pins a woken session to the actuator's own build\nexec "${opts.node}" "${opts.binJs}" "$@"\n`;

  try {
    if (readFileSync(shim, 'utf8') === body) return dir;
  } catch {
    /* absent, unreadable, or stale — fall through and (re)write it */
  }

  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(shim, body);
    chmodSync(shim, 0o755); // `command -v` only finds it if it is executable
    return dir;
  } catch {
    return undefined;
  }
}

/**
 * The spawn environment for a woken harness: the inherited env, `wake` provenance, and PATH with the
 * pinned shim FIRST. Prepending is the whole point — `/opt/homebrew/bin` is already on the host's
 * PATH, so anything appended loses to the frozen tarball.
 */
export function wakeEnv(base: NodeJS.ProcessEnv, pinnedDir: string | undefined): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...base, MUSTERD_PROVENANCE: 'wake' };
  if (!pinnedDir) return env;
  env['PATH'] = base['PATH'] ? `${pinnedDir}:${base['PATH']}` : pinnedDir;
  return env;
}
