/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalPreviewRouteImport } from './routes/approval-preview'
import { Route as IndexRouteImport } from './routes/index'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalPreviewRoute = ApprovalPreviewRouteImport.update({
  id: '/approval-preview',
  path: '/approval-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-preview': typeof ApprovalPreviewRoute
  '/audit': typeof AuditRoute
  '/live': typeof LiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-preview': typeof ApprovalPreviewRoute
  '/audit': typeof AuditRoute
  '/live': typeof LiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-preview': typeof ApprovalPreviewRoute
  '/audit': typeof AuditRoute
  '/live': typeof LiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/approval-preview' | '/audit' | '/live'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approval-preview' | '/audit' | '/live'
  id: '__root__' | '/' | '/approval-preview' | '/audit' | '/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalPreviewRoute: typeof ApprovalPreviewRoute
  AuditRoute: typeof AuditRoute
  LiveRoute: typeof LiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-preview': {
      id: '/approval-preview'
      path: '/approval-preview'
      fullPath: '/approval-preview'
      preLoaderRoute: typeof ApprovalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalPreviewRoute: ApprovalPreviewRoute,
  AuditRoute: AuditRoute,
  LiveRoute: LiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
