/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficePreviewRouteImport } from './routes/office-preview'
import { Route as LiveRouteImport } from './routes/live'
import { Route as CharacterSheetRouteImport } from './routes/character-sheet'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const OfficePreviewRoute = OfficePreviewRouteImport.update({
  id: '/office-preview',
  path: '/office-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterSheetRoute = CharacterSheetRouteImport.update({
  id: '/character-sheet',
  path: '/character-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BoardRoute: typeof BoardRoute
  BroadcastRoute: typeof BroadcastRoute
  CharacterSheetRoute: typeof CharacterSheetRoute
  LiveRoute: typeof LiveRoute
  OfficePreviewRoute: typeof OfficePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/office-preview': {
      id: '/office-preview'
      path: '/office-preview'
      fullPath: '/office-preview'
      preLoaderRoute: typeof OfficePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-sheet': {
      id: '/character-sheet'
      path: '/character-sheet'
      fullPath: '/character-sheet'
      preLoaderRoute: typeof CharacterSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BoardRoute: BoardRoute,
  BroadcastRoute: BroadcastRoute,
  CharacterSheetRoute: CharacterSheetRoute,
  LiveRoute: LiveRoute,
  OfficePreviewRoute: OfficePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
