/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as OfficePreviewRouteImport } from './routes/office-preview'
import { Route as LiveRouteImport } from './routes/live'
import { Route as CharacterSheetRouteImport } from './routes/character-sheet'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficePreviewRoute = OfficePreviewRouteImport.update({
  id: '/office-preview',
  path: '/office-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterSheetRoute = CharacterSheetRouteImport.update({
  id: '/character-sheet',
  path: '/character-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/broadcast': typeof BroadcastRoute
  '/character-sheet': typeof CharacterSheetRoute
  '/live': typeof LiveRoute
  '/office-preview': typeof OfficePreviewRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
    | '/roadmap'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/blog/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
    | '/roadmap'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/blog'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/board'
    | '/broadcast'
    | '/character-sheet'
    | '/live'
    | '/office-preview'
    | '/roadmap'
    | '/blog/$slug'
    | '/docs/$slug'
    | '/blog/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BoardRoute: typeof BoardRoute
  BroadcastRoute: typeof BroadcastRoute
  CharacterSheetRoute: typeof CharacterSheetRoute
  LiveRoute: typeof LiveRoute
  OfficePreviewRoute: typeof OfficePreviewRoute
  RoadmapRoute: typeof RoadmapRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsSlugRoute: typeof DocsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-preview': {
      id: '/office-preview'
      path: '/office-preview'
      fullPath: '/office-preview'
      preLoaderRoute: typeof OfficePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-sheet': {
      id: '/character-sheet'
      path: '/character-sheet'
      fullPath: '/character-sheet'
      preLoaderRoute: typeof CharacterSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BoardRoute: BoardRoute,
  BroadcastRoute: BroadcastRoute,
  CharacterSheetRoute: CharacterSheetRoute,
  LiveRoute: LiveRoute,
  OfficePreviewRoute: OfficePreviewRoute,
  RoadmapRoute: RoadmapRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
