import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { checkEatenSections, checkWiki } from './check-wiki.ts';
import { renderIndex } from './wiki-index.ts';

const dirs: string[] = [];
function fixture(pages: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'wiki-test-'));
  dirs.push(dir);
  for (const [name, body] of Object.entries(pages)) writeFileSync(join(dir, name), body);
  return dir;
}
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

describe('renderIndex', () => {
  it('derives one entry per page from H1 + first body line, sorted, excluding README and INDEX', () => {
    const dir = fixture({
      'b-topic.md': '# Topic B\n\nSummary of B.\n\n## More\n',
      'a-topic.md': '# Topic A\n\nSummary of A.\n',
      'README.md': '# Wiki\n\nConventions.\n',
      'INDEX.md': 'stale\n',
    });
    const out = renderIndex(dir);
    expect(out).toContain('generated by `pnpm wiki:index` — do not edit');
    const lines = out.split('\n').filter((l) => l.startsWith('- '));
    expect(lines).toEqual([
      '- [Topic A](a-topic.md) — Summary of A.',
      '- [Topic B](b-topic.md) — Summary of B.',
    ]);
  });

  /* Labeling a claim must not edit the index. Both halves of an entry can carry a marker: a page
   * whose H1 is itself a dated claim, and a summary line that is one. */
  it('strips claim markers from the H1 and the summary it quotes', () => {
    const dir = fixture({
      'a-topic.md':
        '# Topic A never fires (2026-01-01; falsify: x) <!-- claim: defect -->\n\nSummary of A (2026-01-01; falsify: y). <!-- claim: other -->\n',
    });
    expect(
      renderIndex(dir)
        .split('\n')
        .filter((l) => l.startsWith('- ')),
    ).toEqual([
      '- [Topic A never fires (2026-01-01; falsify: x)](a-topic.md) — Summary of A (2026-01-01; falsify: y).',
    ]);
  });

  it('throws, naming the file, when a page lacks an H1 or a summary line', () => {
    const dir = fixture({ 'bad.md': 'no heading here\n' });
    expect(() => renderIndex(dir)).toThrow(/bad\.md/);
  });
});

describe('checkWiki', () => {
  const good = {
    'a.md':
      '# A\n\nFine page.\n\nThe daemon never installs deps (2026-07-31; falsify: read service.ts). See [B](b.md).\n',
    'b.md': '# B\n\nAlso fine.\n',
  };
  const withIndex = (pages: Record<string, string>) => {
    const dir = fixture(pages);
    writeFileSync(join(dir, 'INDEX.md'), renderIndex(dir));
    return dir;
  };

  it('passes a synced index, dated claims, live links', () => {
    expect(checkWiki(withIndex(good))).toEqual([]);
  });

  it('fails when INDEX.md drifts from the pages', () => {
    const dir = withIndex(good);
    writeFileSync(join(dir, 'a.md'), '# A retitled\n\nFine page.\n');
    expect(checkWiki(dir).join('\n')).toMatch(/INDEX\.md.*wiki:index/);
  });

  it('fails an undated defect-shaped claim, naming file and line', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\nautorefresh never installs deps.\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*date/);
  });

  /* The blind spot that motivated the widening: every one of these passed GREEN undated before
   * 2026-08-24, and they are the family the team was finding most (config.modelDrift,
   * neverExercised, ReconcileResult.errors, OccupiedFrame.charter). Kept as a corpus rather than
   * one example, because the failure being guarded against is the phrase list going stale — a
   * single case would be satisfied by a single synonym. */
  it.each([
    'ReconcileResult.errors is read by nothing, so a corrupt seat file vanishes.',
    'OccupiedFrame.charter is populated by nothing.',
    'The metric is populated by none of the five sites that build the frame.',
    'The value is computed and never used.',
    'The return value is discarded by every caller.',
    'The paragraph is silently deleted by zod .strip().',
    "The doctor's line is reaching no reader.",
    'The charter is served to nobody.',
    'This instrument has never been read.',
    'Nothing counts the repeats.',
    'The field is stored but never served.',
  ])('fails an undated "reaches nobody" claim: %s', (claim) => {
    const dir = withIndex({ 'a.md': `# A\n\nSummary.\n\n${claim}\n` });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*date/);
  });

  /* Both halves of the transitive-verb discriminator. "never read X as Y" is ADVICE and must stay
   * green; "simply never read." is an assertion and must go red. An earlier fix required a clause
   * END after the verb and passed the first case while losing the second. */
  it('does not lint imperative advice that opens its clause with the verb', () => {
    const dir = withIndex({
      'a.md':
        '# A\n\nSummary.\n\nCLI send costs 650 ms — never read CLI latency as transport latency.\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });

  it('still lints the same verb used as an assertion, with a subject in front of it', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\nThe tiebreak was persisted and simply never read.\n',
    });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*date/);
  });

  it('ignores defect-shaped phrases inside fenced code blocks', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\n```\nthis never runs\n```\n' });
    expect(checkWiki(dir)).toEqual([]);
  });

  it('fails a dead intra-wiki link', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSee [gone](missing.md).\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md.*missing\.md/);
  });

  /* #1431 shipped leftover `<<<<<<< HEAD` / `>>>>>>>` markers into cloud-seat-from-inside.md
   * (925b9e70). wiki:check was green: it never looked. The production mutant is those two
   * lines on a live page; `=======` is not flagged on its own (setext underline). */
  it('fails a leftover git conflict marker, naming file and line', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n<<<<<<< HEAD\nkept\n=======\nincoming\n>>>>>>> ebf56712\n',
    });
    const out = checkWiki(dir).join('\n');
    expect(out).toMatch(/a\.md:5.*conflict/);
    expect(out).toMatch(/a\.md:9.*conflict/);
  });

  it('ignores conflict-marker-shaped text inside a fenced code block', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n```\n<<<<<<< HEAD\n```\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });
});

describe('checkWiki — orphaned sections', () => {
  const withIndex = (pages: Record<string, string>) => {
    const dir = fixture(pages);
    writeFileSync(join(dir, 'INDEX.md'), renderIndex(dir));
    return dir;
  };

  it('fails a heading with no body before the next heading, naming file and line', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Eaten\n\n## Next\n\nBody here.\n',
    });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*Eaten/);
  });

  it('fails a trailing heading left with no body at end of file', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\n## Dangling\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*Dangling/);
  });

  it('accepts a heading whose body is a fenced code block', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Recipe\n\n```bash\nrun it\n```\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });

  it('ignores headings inside fenced code blocks', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Template\n\n```markdown\n# <Topic>\n\n## <Section>\n```\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });
});

describe('checkEatenSections (diff-aware)', () => {
  // The #813 shape: the heading line was REPLACED, so its body was absorbed into the section above.
  const base = new Map([
    [
      'a.md',
      '# A\n\nSummary.\n\n## Kept\n\nKept body.\n\n## Eaten (2026-01-01)\n\nOrphan body line.\n',
    ],
  ]);

  it('flags a heading removed while its body survives absorbed into a neighbour', () => {
    const current = new Map([
      ['a.md', '# A\n\nSummary.\n\n## Kept\n\nKept body.\n\nOrphan body line.\n'],
    ]);
    expect(checkEatenSections(base, current).join('\n')).toMatch(/a\.md.*Eaten/);
  });

  it('allows a deliberate deletion of the whole section, heading and body together', () => {
    const current = new Map([['a.md', '# A\n\nSummary.\n\n## Kept\n\nKept body.\n']]);
    expect(checkEatenSections(base, current)).toEqual([]);
  });

  it('allows a retitle — heading text changes but the body still opens its own section', () => {
    const current = new Map([
      [
        'a.md',
        '# A\n\nSummary.\n\n## Kept\n\nKept body.\n\n## Renamed (2026-01-01)\n\nOrphan body line.\n',
      ],
    ]);
    expect(checkEatenSections(base, current)).toEqual([]);
  });

  /* Adding a label to an existing claim is not a retitle and not an eaten section — it is the
   * migration that introduced markers, and unguarded it flagged five real pages at once. */
  it('says nothing when a heading and its body only gain claim markers', () => {
    // Both lines must carry one for this to bite: the marked heading drops out of `headingsAfter`,
    // and the marked body line stops matching `stillOpens` — so the old body text is found only as
    // a SUBSTRING of the marked line and the section reads as absorbed. That is precisely what
    // happened to five real pages on the migration commit.
    const markedBase = new Map([
      [
        'a.md',
        '# A\n\nSummary.\n\n## Kept\n\nKept body.\n\n## Eaten (2026-01-01)\n\nOrphan body (2026-01-01; falsify: x).\n',
      ],
    ]);
    const current = new Map([
      [
        'a.md',
        '# A\n\nSummary.\n\n## Kept\n\nKept body.\n\n## Eaten (2026-01-01) <!-- claim: other -->\n\nOrphan body (2026-01-01; falsify: x). <!-- claim: defect -->\n',
      ],
    ]);
    expect(checkEatenSections(markedBase, current)).toEqual([]);
  });

  it('says nothing about a page that did not exist at the base', () => {
    expect(checkEatenSections(new Map(), base)).toEqual([]);
  });
});
