import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { checkWiki } from './check-wiki.ts';
import { renderIndex } from './wiki-index.ts';

const dirs: string[] = [];
function fixture(pages: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'wiki-test-'));
  dirs.push(dir);
  for (const [name, body] of Object.entries(pages)) writeFileSync(join(dir, name), body);
  return dir;
}
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

describe('renderIndex', () => {
  it('derives one entry per page from H1 + first body line, sorted, excluding README and INDEX', () => {
    const dir = fixture({
      'b-topic.md': '# Topic B\n\nSummary of B.\n\n## More\n',
      'a-topic.md': '# Topic A\n\nSummary of A.\n',
      'README.md': '# Wiki\n\nConventions.\n',
      'INDEX.md': 'stale\n',
    });
    const out = renderIndex(dir);
    expect(out).toContain('generated by `pnpm wiki:index` — do not edit');
    const lines = out.split('\n').filter((l) => l.startsWith('- '));
    expect(lines).toEqual([
      '- [Topic A](a-topic.md) — Summary of A.',
      '- [Topic B](b-topic.md) — Summary of B.',
    ]);
  });

  it('throws, naming the file, when a page lacks an H1 or a summary line', () => {
    const dir = fixture({ 'bad.md': 'no heading here\n' });
    expect(() => renderIndex(dir)).toThrow(/bad\.md/);
  });
});

describe('checkWiki', () => {
  const good = {
    'a.md':
      '# A\n\nFine page.\n\nThe daemon never installs deps (2026-07-31; falsify: read service.ts). See [B](b.md).\n',
    'b.md': '# B\n\nAlso fine.\n',
  };
  const withIndex = (pages: Record<string, string>) => {
    const dir = fixture(pages);
    writeFileSync(join(dir, 'INDEX.md'), renderIndex(dir));
    return dir;
  };

  it('passes a synced index, dated claims, live links', () => {
    expect(checkWiki(withIndex(good))).toEqual([]);
  });

  it('fails when INDEX.md drifts from the pages', () => {
    const dir = withIndex(good);
    writeFileSync(join(dir, 'a.md'), '# A retitled\n\nFine page.\n');
    expect(checkWiki(dir).join('\n')).toMatch(/INDEX\.md.*wiki:index/);
  });

  it('fails an undated defect-shaped claim, naming file and line', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\nautorefresh never installs deps.\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*date/);
  });

  it('ignores defect-shaped phrases inside fenced code blocks', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\n```\nthis never runs\n```\n' });
    expect(checkWiki(dir)).toEqual([]);
  });

  it('fails a dead intra-wiki link', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSee [gone](missing.md).\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md.*missing\.md/);
  });
});

describe('checkWiki — orphaned sections', () => {
  const withIndex = (pages: Record<string, string>) => {
    const dir = fixture(pages);
    writeFileSync(join(dir, 'INDEX.md'), renderIndex(dir));
    return dir;
  };

  it('fails a heading with no body before the next heading, naming file and line', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Eaten\n\n## Next\n\nBody here.\n',
    });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*Eaten/);
  });

  it('fails a trailing heading left with no body at end of file', () => {
    const dir = withIndex({ 'a.md': '# A\n\nSummary.\n\n## Dangling\n' });
    expect(checkWiki(dir).join('\n')).toMatch(/a\.md:5.*Dangling/);
  });

  it('accepts a heading whose body is a fenced code block', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Recipe\n\n```bash\nrun it\n```\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });

  it('ignores headings inside fenced code blocks', () => {
    const dir = withIndex({
      'a.md': '# A\n\nSummary.\n\n## Template\n\n```markdown\n# <Topic>\n\n## <Section>\n```\n',
    });
    expect(checkWiki(dir)).toEqual([]);
  });
});
