/*
 * Derive docs/wiki/INDEX.md from the pages themselves — H1 + first body line per page.
 *
 * The index is GENERATED because a hand-written one goes stale against its own detail, and the
 * index is what gets read: on 2026-08-12 a stale one-line summary contradicted its own topic file
 * and a seat broadcast the stale claim to seven seats. A summary generated from the detail cannot
 * drift from it. (Memory reexamination spec, finding 2.)
 *
 *   pnpm wiki:index   — regenerate docs/wiki/INDEX.md
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const WIKI_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'wiki');
const EXCLUDED = new Set(['README.md', 'INDEX.md']);

export function renderIndex(dir: string): string {
  const entries: string[] = [];
  for (const name of readdirSync(dir)
    .filter((f) => f.endsWith('.md') && !EXCLUDED.has(f))
    .sort()) {
    const lines = readFileSync(join(dir, name), 'utf8').split('\n');
    const h1 = lines[0]?.match(/^#\s+(.+)$/)?.[1];
    const summary = lines
      .slice(1)
      .find((l) => l.trim() !== '' && !l.startsWith('#'))
      ?.trim();
    if (!h1 || !summary)
      throw new Error(
        `${name}: needs an H1 on line 1 and a one-line summary as the first body line`,
      );
    entries.push(`- [${h1}](${name}) — ${summary}`);
  }
  return [
    '# Wiki index',
    '',
    '<!-- generated by `pnpm wiki:index` — do not edit; `pnpm wiki:check` enforces sync -->',
    '',
    ...entries,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(WIKI_DIR, 'INDEX.md'), renderIndex(WIKI_DIR));
  process.stdout.write('docs/wiki/INDEX.md regenerated\n');
}
