import { describe, expect, it } from 'vitest';
import { blogEntries } from './site-files';
// @ts-expect-error plain .mjs data module
import { DAEMON_ROUTES, PUBLIC_ALLOW } from './stage-allowlist.mjs';

describe('the public-origin allowlist (ADR 302)', () => {
  it('stages exactly the public set', () => {
    expect([...PUBLIC_ALLOW].sort()).toEqual(
      [
        'assets',
        // Staged only while a post exists — an empty section is withheld whole rather than
        // deployed as an index with nothing in it.
        ...(blogEntries().length > 0 ? ['blog'] : []),
        'docs',
        'index.html',
        // Generated by the `musterd-site-files` plugin — see scripts/site-files.ts.
        '_headers',
        'llms.txt',
        'llms-full.txt',
        'robots.txt',
        'sitemap.xml',
      ].sort(),
    );
  });

  it('daemon surfaces are named and disjoint from the allowlist', () => {
    for (const r of ['live', 'board', 'audit', 'approvals', 'broadcast', 'character-sheet', 'office-preview']) {
      expect(DAEMON_ROUTES).toContain(r);
      expect(PUBLIC_ALLOW).not.toContain(r);
    }
  });
});
